name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feat/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Create Pull Request
        if: success()
        run: |
          PR_URL=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"title":"Automated PR: Merging feature branch into master","head":"'${{ github.ref }}'","base":"master","body":"This PR is automatically created by GitHub Actions to merge changes from the feature branch into master.","labels":["automated-pr"]}' \
          https://api.github.com/repos/${{ github.repository }}/pulls | jq -r .html_url)
          echo "Pull request created: $PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Delete branch
        if: success()
        run: |
          git push origin --delete ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}